export const LABEL_LISTA_DE_OURO = 'LISTA DE OURO'
export const SITUACAO_QUALIFICAR = 1
export const SITUACAO_CONVIDAR = 2
export const SITUACAO_APRESENTAR = 3
export const SITUACAO_ACOMPANHAR = 4
export const SITUACAO_FECHAMENTO = 5
export const SITUACAO_FECHADO = 6
export const SITUACAO_REMOVIDO = 7
